"""Add watched and total episodes to progress

Revision ID: edf7f29e2165
Revises: cdca532ef554
Create Date: 2026-07-08 10:49:53.014164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf7f29e2165'
down_revision: Union[str, Sequence[str], None] = 'cdca532ef554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_progress', sa.Column('watched_episodes', sa.Integer(), nullable=True))
    op.add_column('watch_progress', sa.Column('total_episodes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_progress', 'total_episodes')
    op.drop_column('watch_progress', 'watched_episodes')
    # ### end Alembic commands ###
